name: CI

on: [push]
env: 
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} 

jobs:
#   activation:
#     name: activate-unity
#     runs-on: ubuntu-latest
#     steps:
#       - id: getManualLicenseFile
#         name: Get git license
#         uses: webbertakken/unity-request-manual-activation-file@v1.1
#         with: 
# #           unityVersion: 2019.3.1f1
#           unityVersion: 2019.3.0f6
# #           unityVersion: 2019.2.11f1
#       - name: Expose as artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: ${{ steps.getManualLicenseFile.outputs.filePath }}
#           path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  builds:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.3.0f6
        targetPlatform:
#           - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
#           - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#           - iOS # Build an iOS player.
#           - Android # Build an Android .apk standalone app.
#           - WebGL # WebGL.
#           - WSAPlayer # Build an Windows Store Apps player.
#           - PS4 # Build a PS4 Standalone.
#           - XboxOne # Build a Xbox One Standalone.
#           - tvOS # Build to Apple's tvOS platform.
#           - Switch # Build a Nintendo Switch player.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
